### ISSUE TITLE
Example would throw a ReferenceError in ES2015

### ISSUE THREAD

**Issue by JamesHenry** [eaze/ng-classy#1]
Hi there,

Awesome idea - best of luck with it!

It might be seen as a bit picky given this libs great intentions, but I see this quite a lot with current ES2015 stuff, so I just thought I would share...

In your first "boilerplate-heavy" example, I believe your code would throw a ReferenceError according to the ES2015 spec. This is because you are referencing a class before its declaration and, unlike function declarations, class declarations are not hoisted.

Naturally, when running that code today with a transpiler it may work, as ultimately the transpiler is changing the class to a function, but I think it is always best to write in a way that will work as soon as the browser support is there, in accordance with the spec.

Cheers!

James

P.S. Axel is the man: http://www.2ality.com/2015/02/es6-classes-final.html

**Comment by ajoslin** [comment]
It wouldn't, because the example runs inside of an angular function which is called after the class has already been defined.

**Comment by JamesHenry** [comment]
You are totally right, and I did not take the angular part into account - that was actually why I closed the issue.

Sorry for the needless issue, I would have deleted it if github allowed it, and thanks again for this project. I will definitely look to use it in the future.

Thanks!
