### ISSUE TITLE
Add LICENSE file, and publish license metadata to npm (in package.json)

### ISSUE THREAD

**Issue by alexkrauss** [eaze/ng-classy#7]
Currently, this project has not specified a license, which means that hardly anybody can legally use it.

Could you add a license, and include appropriate metadata, such that automated tools like nlf (https://github.com/iandotkelly/nlf) can recognize the license correctly?

See also http://choosealicense.com/

**Comment by alexkrauss** [comment]
Any chance this will happen soon? Must look for alternatives otherwise, or rewrite from scratch...

**Comment by hanford** [comment]
@alexkrauss I'll add one in a couple of hours.

**Comment by alexkrauss** [comment]
Thanks @hanford. However, GPL basically makes this unusable for me in a commercial web site built for a customer. Was rather hoping for something like BSD or MIT...

Anyway, I'll respect your choice.

**Comment by hanford** [comment]
@alexkrauss I'll change it to an MIT License, sorry for the confusion!
